**********************************************************************************************
****	Anisa Lab working file preparation
****	Add Variable and Value Labels 
****	September 3, 2013
**********************************************************************************************


//===========================================================================================//
if LabVar==0 {
label var	GenSp1 		"Code for 1st Isolation (Genus+Specis)"
label var	GenSp2 		"Code for 2nd Isolation (Genus+Specis)"
label var	GenSp3 		"Code for 3rd Isolation (Genus+Specis)"
label var	GenSpName1 	"1st Organism name (Genus+Specis)"
label var	GenSpName2 	"2nd Organism name (Genus+Specis)"
label var	GenSpName3 	"3rd Organism name (Genus+Specis)"
label var	Type1		"IN GENERAL whether 1st Organism is a Definite/Probable Pathogen or Contaminant"
label var	Type2		"IN GENERAL whether 2nd Organism is a Definite/Probable Pathogen or Contaminant"
label var	Type3		"IN GENERAL whether 3rd Organism is a Definite/Probable Pathogen or Contaminant"

label var 	BCCReviewed "Reviewed by the BCC or not?"
label var 	reasonNotReviewed "Reason why a specimen was not reviewed by the committee"
label var 	FinalPathogen "Final pathogen, as determined by the committee"
label var 	FinalDeterminationFrm "From where/ from whom the decision taken"
label var 	GenSpName	"List of all Organism"

label 	var		ChocolateGrowth1	"1st Growth - Culture Result in Chocolate Agar Media"
label 	var		BloodGrowth1		"1st Growth - Culture Result in Blood Agar Media"
label 	var		BloodHaemolysis1	"1st Growth - Culture Result - Haemolysis in Blood Agar Media"
label 	var		McconkeyGrowth1		"1st Growth - Culture Result in Macconkey Agar Media"
label 	var		McconkeyLactose1	"1st Growth - Culture Result - 1st Growth - Lactose Fermenter  in Blood Agar Media"
label 	var		GSType1				"1st Growth - Tests for identification: Gram Stain Type"
label 	var		GSShape1			"1st Growth - Tests for identification: Gram Stain Shape"
label 	var		GSArrangement1		"1st Growth - Tests for identification: Gram Stain Arrangement"
label 	var		Catalase1			"1st Growth - Tests for identification: Catalase test"
label 	var		Coagulase1			"1st Growth - Tests for identification: Coagulase test"
label 	var		Camp1				"1st Growth - Tests for identification: Camp test"
label 	var		Oxidase1			"1st Growth - Tests for identification: Oxidase test"
label 	var		Optochin1			"1st Growth - Tests for identification: Optochin sensitivity test (zone diameter)"
label 	var		Bile1				"1st Growth - Tests for identification: Bile solubility test"
label 	var		XVFactor1			"1st Growth - Tests for identification: XV factor test"
label 	var		TSISlant1			"1st Grrowth- Biochemical Test: TSI-SLANT"
label 	var		TSIButt1			"1st Grrowth- Biochemical Test: TSI-BUTT"
label 	var		TSIGas1				"1st Grrowth- Biochemical Test: TSI-GAS"
label 	var		TSIH2S1				"1st Grrowth- Biochemical Test: TSI-H2S"
label 	var		MIUMotile1			"1st Grrowth- Biochemical Test: MIU-Motile"
label 	var		MIUIndole1			"1st Grrowth- Biochemical Test: MIU-Indole"
label 	var		MIUUrease1			"1st Grrowth- Biochemical Test: MIU-Urease"
label 	var		Citrate1			"1st Grrowth- Biochemical Test: CITRATE"

label 	var		ChocolateGrowth2	"2nd Growth - Culture Result in Chocolate Agar Media"
label 	var		BloodGrowth2		"2nd Growth - Culture Result in Blood Agar Media"
label 	var		BloodHaemolysis2	"2nd Growth - Culture Result - Haemolysis in Blood Agar Media"
label 	var		McconkeyGrowth2		"2nd Growth - Culture Result in Macconkey Agar Media"
label 	var		McconkeyLactose2	"2nd Growth - Culture Result - 2nd Growth - Lactose Fermenter  in Blood Agar Media"
label 	var		GSType2				"2nd Growth - Tests for identification: Gram Stain Type"
label 	var		GSShape2			"2nd Growth - Tests for identification: Gram Stain Shape"
label 	var		GSArrangement2		"2nd Growth - Tests for identification: Gram Stain Arrangement"
label 	var		Catalase2			"2nd Growth - Tests for identification: Catalase test"
label 	var		Coagulase2			"2nd Growth - Tests for identification: Coagulase test"
label 	var		Camp2				"2nd Growth - Tests for identification: Camp test"
label 	var		Oxidase2			"2nd Growth - Tests for identification: Oxidase test"
label 	var		Optochin2			"2nd Growth - Tests for identification: Optochin sensitivity test (zone diameter)"
label 	var		Bile2				"2nd Growth - Tests for identification: Bile solubility test"
label 	var		XVFactor2			"2nd Growth - Tests for identification: XV factor test"
label 	var		TSISlant2			"2nd Grrowth- Biochemical Test: TSI-SLANT"
label 	var		TSIButt2			"2nd Grrowth- Biochemical Test: TSI-BUTT"
label 	var		TSIGas2				"2nd Grrowth- Biochemical Test: TSI-GAS"
label 	var		TSIH2S2				"2nd Grrowth- Biochemical Test: TSI-H2S"
label 	var		MIUMotile2			"2nd Grrowth- Biochemical Test: MIU-Motile"
label 	var		MIUIndole2			"2nd Grrowth- Biochemical Test: MIU-Indole"
label 	var		MIUUrease2			"2nd Grrowth- Biochemical Test: MIU-Urease"
label 	var		Citrate2			"2nd Grrowth- Biochemical Test: CITRATE"

label 	var		ChocolateGrowth3	"3rd Growth - Culture Result in Chocolate Agar Media"
label 	var		BloodGrowth3		"3rd Growth - Culture Result in Blood Agar Media"
label 	var		BloodHaemolysis3	"3rd Growth - Culture Result - Haemolysis in Blood Agar Media"
label 	var		McconkeyGrowth3		"3rd Growth - Culture Result in Macconkey Agar Media"
label 	var		McconkeyLactose3	"3rd Growth - Culture Result - 3rd Growth - Lactose Fermenter  in Blood Agar Media"
label 	var		GSType3				"3rd Growth - Tests for identification: Gram Stain Type"
label 	var		GSShape3			"3rd Growth - Tests for identification: Gram Stain Shape"
label 	var		GSArrangement3		"3rd Growth - Tests for identification: Gram Stain Arrangement"
label 	var		Catalase3			"3rd Growth - Tests for identification: Catalase test"
label 	var		Coagulase3			"3rd Growth - Tests for identification: Coagulase test"
label 	var		Camp3				"3rd Growth - Tests for identification: Camp test"
label 	var		Oxidase3			"3rd Growth - Tests for identification: Oxidase test"
label 	var		Optochin3			"3rd Growth - Tests for identification: Optochin sensitivity test (zone diameter)"
label 	var		Bile3				"3rd Growth - Tests for identification: Bile solubility test"
label 	var		XVFactor3			"3rd Growth - Tests for identification: XV factor test"
label 	var		TSISlant3			"3rd Grrowth- Biochemical Test: TSI-SLANT"
label 	var		TSIButt3			"3rd Grrowth- Biochemical Test: TSI-BUTT"
label 	var		TSIGas3				"3rd Grrowth- Biochemical Test: TSI-GAS"
label 	var		TSIH2S3				"3rd Grrowth- Biochemical Test: TSI-H2S"
label 	var		MIUMotile3			"3rd Grrowth- Biochemical Test: MIU-Motile"
label 	var		MIUIndole3			"3rd Grrowth- Biochemical Test: MIU-Indole"
label 	var		MIUUrease3			"3rd Grrowth- Biochemical Test: MIU-Urease"
label 	var		Citrate3			"3rd Grrowth- Biochemical Test: CITRATE"

label define 	OrgTL 	1 "True Pathogen" 3 "Contamination" 2 "Probable Pathogen" 4 "Not decided" 5 "Not reviewed" 6 "False" 7 "Dropped" 8 "Name missing" 9 "Unknown"
label define	HaemL 	0 "Gamma" 1 "Alpha" 2 "Beta"
label define	YNL		1 "Yes" 2 "No" 9 "Don't know"
label define	PNL		1 "Positive" 2 "Negative" 8 "Not Done" 9 "Not Applicable"
label define 	TypeL	1 "Definite Pathogen" 2 "Probable Pathogen" 3 "Definite Contaminant" 
label define 	FSL 	1 "Final Decision Taken by BCC Group" 2 "Not decided by BCC Group"
label define 	GSTL	1 "Gram positive" 2 "Gram Negative"
label define 	GSSL	1 "Cocci" 2 "Rod" 3 "Coccobacilli"
label define 	GSAL    1 "Single" 2 "Diplococci" 3  "Cluster" 4 "Chain"	
label define	SlntL	1 "Acid" 2 "Alkaline" 3 "No change"
label define 	H2SL 	1 "Huge" 2 "Little" 3 "No" 
label define	findec	1 "Positive" 0"Negative"

label 	val		FinalDeterminationFrm FSL
label 	val		FinalDetermination findec
label 	val		TSIH2S1 H2SL
for 	var		BloodHaemolysis*: label val X HaemL
for 	var		ChocolateGrowth1* BloodGrowth* McconkeyGrowth* TSIGas*: label val X YNL
for 	var 	Type*	:label val X TypeL
for 	var		GSType* : label val X GSTL
for 	var		GSShape* : label val X GSSL
for 	var		GSArrangement* : label val X GSSL
for var Catalase* Coagulase* Camp* Oxidase* Optochin* Bile* XVFactor*: label value X PNL 
for var MIUMotile* MIUIndole* MIUUrease* Citrate*: label value X PNL 
for var TSISlant* TSIButt*: label val X SlntL11

}
//===========================================================================================//
if LabVar==1 {
	label var	AmikacinSen			"Antibiotic sensitivity - Amikacin"
	label var	AmpicillinSen		"Antibiotic sensitivity - Ampicillin"
	label var	AzythromicinSen		"Antibiotic sensitivity - Azythromicin"
	label var	CefuroximeaxetilSen	"Antibiotic sensitivity - Cefuroximeaxetil"
	label var	CefotaximeSen		"Antibiotic sensitivity - Cefotaxime"
	label var	CeftazidimeSen		"Antibiotic sensitivity - Ceftazidime"
	label var	CeftriaxoneSen		"Antibiotic sensitivity - Ceftriaxone"
	label var	CephalexinSen		"Antibiotic sensitivity - Cephalexin"
	label var	ChloramphenicolSen	"Antibiotic sensitivity - Chloramphenicol"
	label var	CiprofloxacinSen	"Antibiotic sensitivity - Ciprofloxacin"
	label var	CloxacillinSen		"Antibiotic sensitivity - Cloxacillin"
	label var	CotrimoxazoleSen	"Antibiotic sensitivity - Cotrimoxazole"
	label var	ErythromicinSen		"Antibiotic sensitivity - Erythromicin"
	label var	GentamicinSen		"Antibiotic sensitivity - Gentamicin"
	label var	ImipenemSen			"Antibiotic sensitivity - Imipenem"
	label var	NalidixicAcidSen	"Antibiotic sensitivity - Nalidixic acid"
	label var	NetilmicinSen		"Antibiotic sensitivity - Netilmicin"
	label var	OxacillinSen		"Antibiotic sensitivity - Oxacillin"
	label var	PenicillinSen		"Antibiotic sensitivity - Penicillin"
	label var	TetracyclineSen		"Antibiotic sensitivity - Tetracycline"
	label var	CefepimeSen			"Antibiotic sensitivity - Cefepime"
	label var	LevofloxacinSen		"Antibiotic sensitivity - Levofloxacin"
	label var	MeropenemSen		"Antibiotic sensitivity - Meropenem"
	label var	AztreonamSen		"Antibiotic sensitivity - Aztreonam"
	label var	CefiximeSen			"Antibiotic sensitivity - Cefixime"
	label var	CarbenicillinSen	"Antibiotic sensitivity - Carbenicillin"
	label var	VancomycinSen		"Antibiotic sensitivity - Vancomycin"
	label var	CefuroximeParenSen	"Antibiotic sensitivity - CefuroximeParen"
	label var	CefuroximeOralSen	"Antibiotic sensitivity - CefuroximeOral"
	label var	ClindamycinSen		"Antibiotic sensitivity - Clindamycin"
	label var	AmoxicillinSen		"Antibiotic sensitivity - Amoxicillin"
	label var	CefoxitinSen		"Antibiotic sensitivity - Cefoxitin"
	label var	FusidicAcidSen		"Antibiotic sensitivity - Fusidic Acid"
	label var	LinezolidSen		"Antibiotic sensitivity - Linezolid"
	label var	MetronidazoleSen	"Antibiotic sensitivity - Metronidazole"
	label var	OfloxacinSen		"Antibiotic sensitivity - Ofloxacin"
	label var	PolymyxinSen		"Antibiotic sensitivity - Polymyxin"
	label var	TazobactamSen		"Antibiotic sensitivity - Tazobactam"
	label var	TobramycinSen		"Antibiotic sensitivity - Tobramycin"
	label var	ClavulanicAcidSen	"Antibiotic sensitivity - Clavulanic"
	label var	OptocinSen			"Antibiotic sensitivity - Optocin"
	label var	NitrofurantoinSen	"Antibiotic sensitivity - Nitrofurantoin"
	label var	CefuroximeSen		"Antibiotic sensitivity - Cefuroxime"
	label var	DoxycyclineSen		"Antibiotic sensitivity - Doxycycline"
	label var	MethicillinSen		"Antibiotic sensitivity - Methicillin"
	label 		define SenL 		1 "Resistant" 2 "Intermediate" 3 "Sensitive" 8 "Not done" 9 "Missing"
	
	label var 	AntValue1			"Disc diffusion (in mm) value: Amikacin"
	label var 	AntValue2			"Disc diffusion (in mm) value: Ampicillin"
	label var 	AntValue3			"Disc diffusion (in mm) value: Azythromicin"
	label var 	AntValue5			"Disc diffusion (in mm) value: Cefotaxime"
	label var 	AntValue6			"Disc diffusion (in mm) value: Ceftazidime"
	label var 	AntValue7			"Disc diffusion (in mm) value: Ceftriaxone"
	label var 	AntValue8			"Disc diffusion (in mm) value: Cephalexin"
	label var 	AntValue9			"Disc diffusion (in mm) value: Chloramphenicol"
	label var 	AntValue10			"Disc diffusion (in mm) value: Ciprofloxacin"
	label var 	AntValue11			"Disc diffusion (in mm) value: Cloxacillin"
	label var 	AntValue12			"Disc diffusion (in mm) value: Cotrimoxazole (Trimethoprim- Sulfamethoxazole)"
	label var 	AntValue13			"Disc diffusion (in mm) value: Erythromicin"
	label var 	AntValue14			"Disc diffusion (in mm) value: Gentamicin"
	label var 	AntValue15			"Disc diffusion (in mm) value: Imipenem"
	label var 	AntValue16			"Disc diffusion (in mm) value: Nalidixic acid"
	label var 	AntValue17			"Disc diffusion (in mm) value: Netilmicin"
	label var 	AntValue19			"Disc diffusion (in mm) value: Oxacillin"
	label var 	AntValue20			"Disc diffusion (in mm) value: Penicillin"
	label var 	AntValue21			"Disc diffusion (in mm) value: Tetracycline"
	label var 	AntValue22			"Disc diffusion (in mm) value: Cefepime"
	label var 	AntValue23			"Disc diffusion (in mm) value: Levofloxacin"
	label var 	AntValue24			"Disc diffusion (in mm) value: Meropenem"
	label var 	AntValue25			"Disc diffusion (in mm) value: Aztreonam"
	label var 	AntValue27			"Disc diffusion (in mm) value: Cefixime"
	label var 	AntValue30			"Disc diffusion (in mm) value: Carbenicillin"
	label var 	AntValue32			"Disc diffusion (in mm) value: Vancomycin"
	label var 	AntValue33			"Disc diffusion (in mm) value: Cefuroxim(parenteral)"
	label var 	AntValue34			"Disc diffusion (in mm) value: Cefuroxime (oral)"
	label var 	AntValue35			"Disc diffusion (in mm) value: Clindamycin"
	label var 	AntValue36			"Disc diffusion (in mm) value: Amoxicillin"
	label var 	AntValue37			"Disc diffusion (in mm) value: Cefoxitin"
	label var 	AntValue38			"Disc diffusion (in mm) value: Fusidic acid"
	label var 	AntValue39			"Disc diffusion (in mm) value: Linezolid"
	label var 	AntValue40			"Disc diffusion (in mm) value: Metronidazole"
	label var 	AntValue41			"Disc diffusion (in mm) value: Ofloxacin"
	label var 	AntValue42			"Disc diffusion (in mm) value: Polymyxin B"
	label var 	AntValue43			"Disc diffusion (in mm) value: Tazobactam"
	label var 	AntValue44			"Disc diffusion (in mm) value: Tobramycin"
	label var 	AntValue46			"Disc diffusion (in mm) value: Clavulanic acid "
	
	label var 	EStpValue1			"MIC (µg/ml) value: Amikacin"
	label var 	EStpValue2			"MIC (µg/ml) value: Ampicillin"
	label var 	EStpValue3			"MIC (µg/ml) value: Azythromicin"
	label var 	EStpValue5			"MIC (µg/ml) value: Cefotaxime"
	label var 	EStpValue6			"MIC (µg/ml) value: Ceftazidime"
	label var 	EStpValue7			"MIC (µg/ml) value: Ceftriaxone"
	label var 	EStpValue8			"MIC (µg/ml) value: Cephalexin"
	label var 	EStpValue9			"MIC (µg/ml) value: Chloramphenicol"
	label var 	EStpValue10			"MIC (µg/ml) value: Ciprofloxacin"
	label var 	EStpValue11			"MIC (µg/ml) value: Cloxacillin"
	label var 	EStpValue12			"MIC (µg/ml) value: Cotrimoxazole (Trimethoprim- Sulfamethoxazole)"
	label var 	EStpValue13			"MIC (µg/ml) value: Erythromicin"
	label var 	EStpValue14			"MIC (µg/ml) value: Gentamicin"
	label var 	EStpValue15			"MIC (µg/ml) value: Imipenem"
	label var 	EStpValue16			"MIC (µg/ml) value: Nalidixic acid"
	label var 	EStpValue17			"MIC (µg/ml) value: Netilmicin"
	label var 	EStpValue19			"MIC (µg/ml) value: Oxacillin"
	label var 	EStpValue20			"MIC (µg/ml) value: Penicillin"
	label var 	EStpValue21			"MIC (µg/ml) value: Tetracycline"
	label var 	EStpValue22			"MIC (µg/ml) value: Cefepime"
	label var 	EStpValue23			"MIC (µg/ml) value: Levofloxacin"
	label var 	EStpValue24			"MIC (µg/ml) value: Meropenem"
	label var 	EStpValue25			"MIC (µg/ml) value: Aztreonam"
	label var 	EStpValue27			"MIC (µg/ml) value: Cefixime"
	label var 	EStpValue30			"MIC (µg/ml) value: Carbenicillin"
	label var 	EStpValue32			"MIC (µg/ml) value: Vancomycin"
	label var 	EStpValue33			"MIC (µg/ml) value: Cefuroxim(parenteral)"
	label var 	EStpValue34			"MIC (µg/ml) value: Cefuroxime (oral)"
	label var 	EStpValue35			"MIC (µg/ml) value: Clindamycin"
	label var 	EStpValue36			"MIC (µg/ml) value: Amoxicillin"
	label var 	EStpValue37			"MIC (µg/ml) value: Cefoxitin"
	label var 	EStpValue38			"MIC (µg/ml) value: Fusidic acid"
	label var 	EStpValue39			"MIC (µg/ml) value: Linezolid"
	label var 	EStpValue40			"MIC (µg/ml) value: Metronidazole"
	label var 	EStpValue41			"MIC (µg/ml) value: Ofloxacin"
	label var 	EStpValue42			"MIC (µg/ml) value: Polymyxin B"
	label var 	EStpValue43			"MIC (µg/ml) value: Tazobactam"
	label var 	EStpValue44			"MIC (µg/ml) value: Tobramycin"
	label var 	EStpValue46			"MIC (µg/ml) value: Clavulanic acid "
	
	for 		var *Sen: 			label val X SenL
	}
//===========================================================================================//
if 	LabVar==2 {
		label var 	SpecimenID			"Specimen ID"
		label var 	ReceiveDt			"Specimen receive date at Lab"
		label var 	Age					"Age of the child"
		label var 	Sex					"Child's sex"
		label var 	Result				"BACTEC result of blood"
		label var 	PutDate				"Put in date"
		label var 	PutTime				"Put in time"
		label var 	BeepDate			"Beep date"
		label var 	BeepTime			"Beep time"
		label var 	OutDate				"Take out date"
		label var 	OutTime				"Take out time"
		label var 	PutDtTm				"Put in date & time"
		label var 	BeepDtTm			"Beep date & time"
		label var 	OutDtTm				"Take out date & time"
		label var 	BeepGSType			"Gram stain of Beep+ve - Type"
		label var 	BeepGSShape			"Gram stain of Beep+ve - Shape"
		label var 	BeepGSArra			"Gram stain of Beep+ve - Arrangement"
		label var 	SubCul				"Culture result of BEEP+VE"
		label var 	BeepCul				"BEEP+VE CULTURE-VE  broth preserved 1ml for Molecular test"
		label var 	ICT					"ICT  (For S. pneumoniae)"
		label var 	CulGent				"Sub-culture on GENTAMICIN Blood Agar for Recovery of Pneumococcus"
		label var 	Serotype			"Serotype"
		label var 	DetecMethod			"Detection method "
		label var 	Antibiogram			"Antibiogram done"

		label var 	AmikacinDisc		"Antibiogram - Disc diffusion value of Amikacin(in mm)"
		label var 	AmpicillinDisc		"Antibiogram - Disc diffusion value of Ampicillin(in mm)"
		label var 	AzythromicinDisc	"Antibiogram - Disc diffusion value of Azythromicin(in mm)"
		label var 	CefuroximeParenDisc	"Antibiogram - Disc diffusion value of CefuroximeParen(in mm)"
		label var 	CefuroximeOralDisc	"Antibiogram - Disc diffusion value of CefuroximeOral(in mm)"
		label var 	CefotaximeDisc		"Antibiogram - Disc diffusion value of Cefotaxime(in mm)"
		label var 	CeftazidimeDisc		"Antibiogram - Disc diffusion value of Ceftazidime(in mm)"
		label var 	CeftriaxoneDisc		"Antibiogram - Disc diffusion value of Ceftriaxone(in mm)"
		label var 	CephalexinDisc		"Antibiogram - Disc diffusion value of Cephalexin(in mm)"
		label var 	ChloramphenicolDisc	"Antibiogram - Disc diffusion value of Chloramphenicol(in mm)"
		label var 	CiprofloxacinDisc	"Antibiogram - Disc diffusion value of Ciprofloxacin(in mm)"
		label var 	CloxacillinDisc		"Antibiogram - Disc diffusion value of Cloxacillin(in mm)"
		label var 	CotrimoxazoleDisc	"Antibiogram - Disc diffusion value of Cotrimoxazole(in mm)"
		label var 	ErythromicinDisc	"Antibiogram - Disc diffusion value of Erythromicin(in mm)"
		label var 	GentamicinDisc		"Antibiogram - Disc diffusion value of Gentamicin(in mm)"
		label var 	ImipenemDisc		"Antibiogram - Disc diffusion value of Imipenem(in mm)"
		label var 	NalidixicDisc		"Antibiogram - Disc diffusion value of Nalidixic(in mm)"
		label var 	NetilmicinDisc		"Antibiogram - Disc diffusion value of Netilmicin(in mm)"
		label var 	OxacillinDisc		"Antibiogram - Disc diffusion value of Oxacillin(in mm)"
		label var 	PenicillinDisc		"Antibiogram - Disc diffusion value of Penicillin(in mm)"
		label var 	TetracyclineDisc	"Antibiogram - Disc diffusion value of Tetracycline(in mm)"
		label var 	CefepimeDisc		"Antibiogram - Disc diffusion value of Cefepime(in mm)"
		label var 	LevofloxacinDisc	"Antibiogram - Disc diffusion value of Levofloxacin(in mm)"
		label var 	MeropenemDisc		"Antibiogram - Disc diffusion value of Meropenem(in mm)"
		label var 	AztreonamDisc		"Antibiogram - Disc diffusion value of Aztreonam(in mm)"
		label var 	CefiximeDisc		"Antibiogram - Disc diffusion value of Cefixime(in mm)"
		label var 	CarbenicillinDisc	"Antibiogram - Disc diffusion value of Carbenicillin(in mm)"
		label var 	VancomycinDisc		"Antibiogram - Disc diffusion value of Vancomycin(in mm)"
		label var 	ClindamycinDisc		"Antibiogram - Disc diffusion value of Clindamycin(in mm)"
		label var 	AmoxicillinDisc		"Antibiogram - Disc diffusion value of Amoxicillin(in mm)"
		label var 	CefoxitinDisc		"Antibiogram - Disc diffusion value of Cefoxitin(in mm)"
		label var 	FusidicDisc			"Antibiogram - Disc diffusion value of Fusidic(in mm)"
		label var 	LinezolidDisc		"Antibiogram - Disc diffusion value of Linezolid(in mm)"
		label var 	MetronidazoleDisc	"Antibiogram - Disc diffusion value of Metronidazole(in mm)"
		label var 	OfloxacinDisc		"Antibiogram - Disc diffusion value of Ofloxacin(in mm)"
		label var 	PolymyxinDisc		"Antibiogram - Disc diffusion value of Polymyxin(in mm)"
		label var 	TazobactamDisc		"Antibiogram - Disc diffusion value of Tazobactam(in mm)"
		label var 	TobramycinDisc		"Antibiogram - Disc diffusion value of Tobramycin(in mm)"
		label var 	ClavulanicDisc		"Antibiogram - Disc diffusion value of Clavulanic(in mm)"
		label var 	OrgAntibiogram		"Antibiogram of organism"
		label var 	API					"API"
		label var 	EnteroFinalScore	"Enterobacteriaceae Final Score"
		label var 	EnteroName			"Enterobacteriaceae Name "
		label var 	NonEnteroName		"Non-enterobacteriaceae Name"
		label var 	NonEnteroFinalScore	"Non-enterobacteriaceae Final Score"
		label var	GenSp1				"1st isolates code"
		label var	GenSp2				"2st isolates code"
		label var	GenSp3				"3st isolates code"
		label var	GenSpName1			"1st isolates name (Genus+Species)"
		label var	GenSpName2			"2nd isolates name (Genus+Species)"
		label var	GenSpName3			"3rd isolates name (Genus+Species)"
		label var 	GenSpName			"Combined isolates name"
		label var 	TTPHr				"TTP in hours (if CS + ve)"
		label var 	TTPDy				"TTP in days (if CS + ve)"
		  
		label 	define 	PNLab		1 "Positive" 2 "Negative" 3 "Intermediate" 9 "Not done"
		label	define 	BPN1L		1 "Beep Positive" 2 "Beep Negetive" 8 "Not done" 9 "Missing"
		label	define 	YN1L		0 "None" 1 "Yes" 2 "No" 8 "Not done" 9 "Don't know"
		label	define 	PN1L		1 "Positive" 2 "Negetive" 8 "Not done" 9 "Missing"
		label	define 	GrthL		1 "Growth" 2 "No growth" 9 "Missing"
		label	define 	BpResL		1 "Single growth" 2 "No growth" 3 "Multiple growth" 9 "Missing"
		label	define 	GrStTL		1 "Gram positive" 2 "Gram Negative" 
		label	define 	GrStSL		1 "Cocci" 2 "Rod" 3 "Coccobacilli"
		label	define 	GrStAL		1 "Single" 2 "Diplococci" 3 "Cluster" 4 "Chain"
		label	define	DetL		1 "Quellung" 2 "Latex"  3 "Serum agglutination test" 4 "PCR"                                                        
		label	define 	AntL		1 "Done for Org-1" 2 "Done for Org-2"  3 "Done for Org-3" 8 "Not done" 9 "Not applicable"                                                        
		label	define 	MisL		999 "Missing" 9999 "Missing"
		
		label 	val		BeepGSType		GrStTL
		label 	val		BeepGSShape		GrStSL
		label 	val		BeepGSArra		GrStAL
		label 	val		DetecMethod		DetL
		label 	val		Result			BPN1L
		label 	val		SubCul			BpResL
		label 	val		BeepCul			YN1L	
		label 	val		ICT				PN1L
		label 	val		CulGent			GrthL
		label 	val		Antibiogram		AntL
		label 	val		API				AntL
		for var TTPHr TTPDy: label val X MisL
}
//===========================================================================================//
if LabVar==3 {
		label var		EschColi		"Organism: Escherichia coli"
		label var		SalmEnter		"Organism: Salmonella enteritidis"
		label var		SalmPTyphi		"Organism: Salmonella paratyphi A"
		label var		SalmSp		 	"Organism: Salmonella sp."
		label var		SalmTyphi		"Organism: Salmonella typhi"
		label var		KlebOxyt		"Organism: Klebsiella oxytoca"
		label var		KlebPneu		"Organism: Klebsiella pneumoniae"
		label var		KlebSp		 	"Organism: Klebsiella sp."
		label var		EnteAerog		"Organism: Enterobacter aerogenes	"
		label var		EnteCloa		"Organism: Enterobacter cloacae	"
		label var		EnteSp		 	"Organism: Enterobacter sp."
		label var		CitrFreun		"Organism: Citrobacter  freundii"
		label var		CitrSp		 	"Organism: Citrobacter  sp."
		label var		SerrMarc		"Organism: Serratia marcescens"
		label var		SerrSp		 	"Organism: Serratia sp."
		label var		ProtMirab		"Organism: Proteus mirabilis"
		label var		ProtSp		 	"Organism: Proteus sp."
		label var		ProtVulg		"Organism: Proteus vulgaris"
		label var		MorgMorg		"Organism: Morganella morganii"
		label var		MorgSp		 	"Organism: Morganella sp."
		label var		ProvAlcal		"Organism: Providencia alcalifaciens"
		label var		ProvRett		"Organism: Providencia rettgeri"
		label var		ProvSp		 	"Organism: Providencia sp."
		label var		ProvStuar		"Organism: Providencia stuartii"
		label var		YersEnter		"Organism: Yersinia enterocolitica"
		label var		YersPest		"Organism: Yersinia pestis"
		label var		YersSp		 	"Organism: Yersinia sp."
		label var		EdwaSp		 	"Organism: Edwardsiella sp."
		label var		EdwaTarda		"Organism: Edwardsiella tarda"
		label var		HafnAlvei		"Organism: Hafnia alvei"
		label var		HafnSp		 	"Organism: Hafnia sp."
		label var		AeroHydr		"Organism: Aeromonas  hydrophila"
		label var		AeroSp		 	"Organism: Aeromonas  sp."
		label var		PlesShigel		"Organism: Plesiomonas shigelloides"
		label var		PlesSp		 	"Organism: Plesiomonas sp."
		label var		VibrSp		 	"Organism: Vibrio sp."
		label var		StapAureus		"Organism: Staphylococcus aureus"
		label var		StapEpider		"Organism: Staphylococcus epidermidis"
		label var		StapSapr		"Organism: Staphylococcus saprophyticus"
		label var		StapSp		 	"Organism: Staphylococcus sp."
		label var		StreAgal		"Organism: Streptococcus agalactiae"
		label var		StrePneu		"Organism: Streptococcus pneumoniae"
		label var		StrePyog		"Organism: Streptococcus pyogenes"
		label var		StreSp		 	"Organism: Streptococcus sp."
		label var		EntercSp		"Organism: Enterococcus sp."
		label var		ListMono		"Organism: Listeria monocytogenes"
		label var		ListSp		 	"Organism: Listeria sp."
		label var		NeisGonor		"Organism: Neisseria gonorrhoeae"
		label var		NeisMenin		"Organism: Neisseria meningitidis"
		label var		PseuAerug		"Organism: Pseudomonas aeruginosa"
		label var		PseuSp		 	"Organism: Pseudomonas sp."
		label var		CampSp		 	"Organism: Campylobacter  sp."
		label var		HaemInfl		"Organism: Haemophilus influenzae"
		label var		HaemPInfl		"Organism: Haemophilus parainfluenzae"
		label var		HaemSp		 	"Organism: Haemophilus sp."
		label var		AcinSp		 	"Organism: Acinetobacter sp."
		label var		FlavSp		 	"Organism: Flavobacterium sp."
		label var		MoreCatar		"Organism: Morexella  catarrahlis"
		label var		AnaeNone		"Organism: Anaerobes None"
		label var		StapCoagNeg		"Organism: Staphylococcus Coagulase negative"
		label var		StrepCoagNeg		"Organism: Streptococcus Coagulase negative"
		label var		StrepOral		"Organism: Streptococcus oralis"
		label var		BacilSp			"Organism: Bacillus Sp."
		label var		CorynSp			"Organism: Corynebacterium Sp."
		label var		ClostPerf		"Organism: Clostridium Perfringens"
		label var		ClostSp			"Organism: Clostridium Sp."
		label var		CampJej			"Organism: Campylobacter Jejuni"
		label var		AlclFaecal		"Organism: Alcligenes Faecalis"
		label var		BrevSp			"Organism: Brevundimonasc Sp."
		label var		BurkSp			"Organism: Burkholderia Sp."
		label var		BurkCep			"Organism: Burkholderia Cepacia"
		label var		MicroSp			"Organism: Micrococcus Sp"
		label var		StenMalt		"Organism: Stenotrophomonas maltophila"
		label var		GrmNegEntr		"Organism: Gram Negative Non-Enterobacteriaceae"
		label var		KocSp			"Organism: Kocuria Sp"
		label var		RhodSp			"Organism: Rhodococcus Sp"
		label var		DipthSp			"Organism: Diptheroids Sp"
		label var		Miss			"Organism: Missing"

		for var 	EschColi- Miss: label val X PNL
}

if LabVar==4 {
	label 		define 	PNLab	1 "Positive" 2 "Negative" 3 "Intermediate" 9 "Not done"
	label 		define 	YNL		0 "No" 1 "Yes" 2 "No" 9 "Missing" 
	for var ABAU- URUP	: label val X PNLab
	
	label var	ABAU	"Acinetobacter baumannii"
	label var	ADEV	"Adenovirus"
	label var	BOP1	"Bordetella pertussis, Bordetella holmesii"
	label var	CHPN	"Chlamydophila pneumoniae"
	label var	CHTR	"Chlamydia trachomatis"
	label var	CYMV	"Cytomegalovirus"
	label var	ECSH	"Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	ENTV1	"Enterovirus 1"
	label var	ENTV2	"Enterovirus 2"
	label var	FLUA	"Influenza type A"
	label var	FLUB	"Influenza type B"
	label var	GADH	"Glyceraldehyde-3-phosphate dehydrogenase"
	label var	GAST	"Streptococus pyogenes"
	label var	GBST	"Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	HIAT	"Haemophilus infuluenzae"
	label var	HITB	"Haemophilus infuluenzae type B"
	label var	HMPV	"Human Metapneumovirus"
	label var	HPEV	"Parechovirus"
	label var	PIV1	"Parainfluenza virus-1"	
	label var	PIV2	"Parainfluenza virus-2"
	label var	PIV3	"Parainfluenza virus-3"
	label var	HSV1	"Herpes Simplex Virus type 1"
	label var	HSV2	"Herpes Simplex Virus type 2"
	label var	IPCO	"Internal Positive Control"	
	label var	KLPN	"Klebsiella pneumoniae"
	label var	MYPN	"Mycoplasma pneumoniae"
	label var	PSAE	"Pseudomonas aeruginosa"
	label var	RESV	"Respiratory Syncytial Virus"
	label var	NMEN	"Neisseria meningitidis"
	label var	RHIV	"Rhinovirus"
	label var	RNP3	"Human RNase P gene"
	label var	RUBV	"Rubella virus"
	label var	SALS	"Salmonella spp"
	label var	STAU	"Staphylococcus aureus"
	label var	STPN	"Streptococcus pneumoniae"
	label var	TOxG	"Toxoplasma gondii"
	label var	URUP	"U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"
}

if LabVar==5 {
//	label 		define 	PNLab	1 "Positive" 2 "Negative" 3 "Intermediate" 9 "Not done"
//	label 		define 	YNL		0 "No" 1 "Yes" 2 "No" 9 "Missing" 
	for var ABAU ADEV BOP1 CHPN CHTR CYMV ECSH ENTV1 ENTV2 FLUA FLUB GADH GAST GBST HIAT HITB HMPV HPEV HSV1 HSV2 IPCO KLPN MYPN NMEN PIV1 PIV2 PIV3 PSAE RESV RHIV RNP3 RUBV SALS STAU STPN TOxG URUP	: label val X PNLab
	
	label var	ABAU	"Detected in Blood: Acinetobacter baumannii"
	label var	ADEV	"Detected in Blood: Adenovirus"
	label var	BOP1	"Detected in Blood: Bordetella pertussis, Bordetella holmesii"
	label var	CHPN	"Detected in Blood: Chlamydophila pneumoniae"
	label var	CHTR	"Detected in Blood: Chlamydia trachomatis"
	label var	CYMV	"Detected in Blood: vCytomegalovirus"
	label var	ECSH	"Detected in Blood: Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	ENTV1	"Detected in Blood: Enterovirus 1"
	label var	ENTV2	"Detected in Blood: Enterovirus 2"
	label var	FLUA	"Detected in Blood: Influenza type A"
	label var	FLUB	"Detected in Blood: Influenza type B"
	label var	GADH	"Detected in Blood: Glyceraldehyde-3-phosphate dehydrogenase"
	label var	GAST	"Detected in Blood: Streptococus pyogenes"
	label var	GBST	"Detected in Blood: Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	HIAT	"Detected in Blood: Haemophilus infuluenzae"
	label var	HITB	"Detected in Blood: Haemophilus infuluenzae type B"
	label var	HMPV	"Detected in Blood: Human Metapneumovirus"
	label var	HPEV	"Detected in Blood: Parechovirus"
	label var	PIV1	"Detected in Blood: Parainfluenza virus-1"	
	label var	PIV2	"Detected in Blood: Parainfluenza virus-2"
	label var	PIV3	"Detected in Blood: Parainfluenza virus-3"
	label var	HSV1	"Detected in Blood: Herpes Simplex Virus type 1"
	label var	HSV2	"Detected in Blood: Herpes Simplex Virus type 2"
	label var	IPCO	"Detected in Blood: Internal Positive Control"	
	label var	KLPN	"Detected in Blood: Klebsiella pneumoniae"
	label var	MYPN	"Detected in Blood: Mycoplasma pneumoniae"
	label var	PSAE	"Detected in Blood: Pseudomonas aeruginosa"
	label var	RESV	"Detected in Blood: Respiratory Syncytial Virus"
	label var	NMEN	"Detected in Blood: Neisseria meningitidis"
	label var	RHIV	"Detected in Blood: Rhinovirus"
	label var	RNP3	"Detected in Blood: Human RNase P gene"
	label var	RUBV	"Detected in Blood: Rubella virus"
	label var	SALS	"Detected in Blood: Salmonella spp"
	label var	STAU	"Detected in Blood: Staphylococcus aureus"
	label var	STPN	"Detected in Blood: Streptococcus pneumoniae"
	label var	TOxG	"Detected in Blood: Toxoplasma gondii"
	label var	URUP	"Detected in Blood: U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"

	label var	CTABAU	"Blood: CT value of Acinetobacter baumannii"
	label var	CTADEV	"Blood: CT value of Adenovirus"
	label var	CTBOP1	"Blood: CT value of Bordetella pertussis, Bordetella holmesii"
	label var	CTCHPN	"Blood: CT value of Chlamydophila pneumoniae"
	label var	CTCHTR	"Blood: CT value of Chlamydia trachomatis"
	label var	CTCYMV	"Blood: CT value of Cytomegalovirus"
	label var	CTECSH	"Blood: CT value of Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	CTENTV1	"Blood: CT value of Enterovirus 1"
	label var	CTENTV2	"Blood: CT value of Enterovirus 2"
	label var	CTFLUA	"Blood: CT value of Influenza type A"
	label var	CTFLUB	"Blood: CT value of Influenza type B"
	label var	CTGADH	"Blood: CT value of Glyceraldehyde-3-phosphate dehydrogenase"
	label var	CTGAST	"Blood: CT value of Streptococus pyogenes"
	label var	CTGBST	"Blood: CT value of Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	CTHIAT	"Blood: CT value of Haemophilus infuluenzae"
	label var	CTHITB	"Blood: CT value of Haemophilus infuluenzae type B"
	label var	CTHMPV	"Blood: CT value of Human Metapneumovirus"
	label var	CTHPEV	"Blood: CT value of Parechovirus"
	label var	CTPIV1	"Blood: CT value of Parainfluenza virus-1"	
	label var	CTPIV2	"Blood: CT value of Parainfluenza virus-2"
	label var	CTPIV3	"Blood: CT value of Parainfluenza virus-3"
	label var	CTHSV1	"Blood: CT value of Herpes Simplex Virus type 1"
	label var	CTHSV2	"Blood: CT value of Herpes Simplex Virus type 2"
	label var	CTIPCO	"Blood: CT value of Internal Positive Control"	
	label var	CTKLPN	"Blood: CT value of Klebsiella pneumoniae"
	label var	CTMYPN	"Blood: CT value of Mycoplasma pneumoniae"
	label var	CTPSAE	"Blood: CT value of Pseudomonas aeruginosa"
	label var	CTRESV	"Blood: CT value of Respiratory Syncytial Virus"
	label var	CTNMEN	"Blood: CT value of Neisseria meningitidis"
	label var	CTRHIV	"Blood: CT value of Rhinovirus"
	label var	CTRNP3	"Blood: CT value of Human RNase P gene"
	label var	CTRUBV	"Blood: CT value of Rubella virus"
	label var	CTSALS	"Blood: CT value of Salmonella spp"
	label var	CTSTAU	"Blood: CT value of Staphylococcus aureus"
	label var	CTSTPN	"Blood: CT value of Streptococcus pneumoniae 1"
	label var	CTTOxG	"Blood: CT value of Toxoplasma gondii"
	label var	CTURUP	"Blood: CT value of U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"

	label var	CTABAUCat	"Blood: CT value classification:  Acinetobacter baumannii"
	label var	CTADEVCat	"Blood: CT value classification:  Adenovirus"
	label var	CTBOP1Cat	"Blood: CT value classification:  Bordetella pertussis, Bordetella holmesii"
	label var	CTCHPNCat	"Blood: CT value classification:  Chlamydophila pneumoniae"
	label var	CTCHTRCat	"Blood: CT value classification:  Chlamydia trachomatis"
	label var	CTCYMVCat	"Blood: CT value classification:  Cytomegalovirus"
	label var	CTECSHCat	"Blood: CT value classification:  Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	CTENTV1Cat	"Blood: CT value classification:  Enterovirus 1"
	label var	CTENTV2Cat	"Blood: CT value classification:  Enterovirus 2"
	label var	CTFLUACat	"Blood: CT value classification:  Influenza type A"
	label var	CTFLUBCat	"Blood: CT value classification:  Influenza type B"
	label var	CTGADHCat	"Blood: CT value classification:  Glyceraldehyde-3-phosphate dehydrogenase"
	label var	CTGASTCat	"Blood: CT value classification:  Streptococus pyogenes"
	label var	CTGBSTCat	"Blood: CT value classification:  Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	CTHIATCat	"Blood: CT value classification:  Haemophilus infuluenzae"
	label var	CTHITBCat	"Blood: CT value classification:  Haemophilus infuluenzae type B"
	label var	CTHMPVCat	"Blood: CT value classification:  Human Metapneumovirus"
	label var	CTHPEVCat	"Blood: CT value classification:  Parechovirus"
	label var	CTPIV1Cat	"Blood: CT value classification:  Parainfluenza virus-1"	
	label var	CTPIV2Cat	"Blood: CT value classification:  Parainfluenza virus-2"
	label var	CTPIV3Cat	"Blood: CT value classification:  Parainfluenza virus-3"
	label var	CTHSV1Cat	"Blood: CT value classification:  Herpes Simplex Virus type 1"
	label var	CTHSV2Cat	"Blood: CT value classification:  Herpes Simplex Virus type 2"
	label var	CTIPCOCat	"Blood: CT value classification:  Internal Positive Control"	
	label var	CTKLPNCat	"Blood: CT value classification:  Klebsiella pneumoniae"
	label var	CTMYPNCat	"Blood: CT value classification:  Mycoplasma pneumoniae"
	label var	CTPSAECat	"Blood: CT value classification:  Pseudomonas aeruginosa"
	label var	CTRESVCat	"Blood: CT value classification:  Respiratory Syncytial Virus"
	label var	CTNMENCat	"Blood: CT value classification:  Neisseria meningitidis"
	label var	CTRHIVCat	"Blood: CT value classification:  Rhinovirus"
	label var	CTRNP3Cat	"Blood: CT value classification:  Human RNase P gene"
	label var	CTRUBVCat	"Blood: CT value classification:  Rubella virus"
	label var	CTSALSCat	"Blood: CT value classification:  Salmonella spp"
	label var	CTSTAUCat	"Blood: CT value classification:  Staphylococcus aureus"
	label var	CTSTPNCat	"Blood: CT value classification:  Streptococcus pneumoniae 1"
	label var	CTTOxGCat	"Blood: CT value classification:  Toxoplasma gondii"
	label var	CTURUPCat	"Blood: CT value classification:  U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"
	label var 	Growth	 	"All Detected in Blood TLDA"
	label var 	NoPos	 	"Total number of organisms detected in Blood TLDA"
	label var 	expRunDate	"Blood TLDA run date"
	}
if LabVar==6 {
//	label 		define 	PNLab	1 "Positive" 2 "Negative" 3 "Intermediate" 9 "Not done"
//	label 		define 	YNL		0 "No" 1 "Yes" 2 "No" 9 "Missing" 
	for var ABAU ADEV BOP1 CHPN CHTR CYMV ECSH ENTV1 ENTV2 FLUA FLUB GADH GAST GBST HIAT HITB HMPV HPEV HSV1 HSV2 IPCO KLPN MYPN NMEN PIV1 PIV2 PIV3 PSAE RESV RHIV RNP3 RUBV SALS STAU STPN TOxG URUP	: label val X PNLab
	
	label var	ABAU	"Detected in NP-OP: Acinetobacter baumannii"
	label var	ADEV	"Detected in NP-OP: Adenovirus"
	label var	BOP1	"Detected in NP-OP: Bordetella pertussis, Bordetella holmesii"
	label var	CHPN	"Detected in NP-OP: Chlamydophila pneumoniae"
	label var	CHTR	"Detected in NP-OP: Chlamydia trachomatis"
	label var	CYMV	"Detected in NP-OP: vCytomegalovirus"
	label var	ECSH	"Detected in NP-OP: Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	ENTV1	"Detected in NP-OP: Enterovirus 1"
	label var	ENTV2	"Detected in NP-OP: Enterovirus 2"
	label var	FLUA	"Detected in NP-OP: Influenza type A"
	label var	FLUB	"Detected in NP-OP: Influenza type B"
	label var	GADH	"Detected in NP-OP: Glyceraldehyde-3-phosphate dehydrogenase"
	label var	GAST	"Detected in NP-OP: Streptococus pyogenes"
	label var	GBST	"Detected in NP-OP: Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	HIAT	"Detected in NP-OP: Haemophilus infuluenzae"
	label var	HITB	"Detected in NP-OP: Haemophilus infuluenzae type B"
	label var	HMPV	"Detected in NP-OP: Human Metapneumovirus"
	label var	HPEV	"Detected in NP-OP: Parechovirus"
	label var	PIV1	"Detected in NP-OP: Parainfluenza virus-1"	
	label var	PIV2	"Detected in NP-OP: Parainfluenza virus-2"
	label var	PIV3	"Detected in NP-OP: Parainfluenza virus-3"
	label var	HSV1	"Detected in NP-OP: Herpes Simplex Virus type 1"
	label var	HSV2	"Detected in NP-OP: Herpes Simplex Virus type 2"
	label var	IPCO	"Detected in NP-OP: Internal Positive Control"	
	label var	KLPN	"Detected in NP-OP: Klebsiella pneumoniae"
	label var	MYPN	"Detected in NP-OP: Mycoplasma pneumoniae"
	label var	PSAE	"Detected in NP-OP: Pseudomonas aeruginosa"
	label var	RESV	"Detected in NP-OP: Respiratory Syncytial Virus"
	label var	NMEN	"Detected in NP-OP: Neisseria meningitidis"
	label var	RHIV	"Detected in NP-OP: Rhinovirus"
	label var	RNP3	"Detected in NP-OP: Human RNase P gene"
	label var	RUBV	"Detected in NP-OP: Rubella virus"
	label var	SALS	"Detected in NP-OP: Salmonella spp"
	label var	STAU	"Detected in NP-OP: Staphylococcus aureus"
	label var	STPN	"Detected in NP-OP: Streptococcus pneumoniae"
	label var	TOxG	"Detected in NP-OP: Toxoplasma gondii"
	label var	URUP	"Detected in NP-OP: U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"

	label var	CTABAU	"NP-OP: CT value of Acinetobacter baumannii"
	label var	CTADEV	"NP-OP: CT value of Adenovirus"
	label var	CTBOP1	"NP-OP: CT value of Bordetella pertussis, Bordetella holmesii"
	label var	CTCHPN	"NP-OP: CT value of Chlamydophila pneumoniae"
	label var	CTCHTR	"NP-OP: CT value of Chlamydia trachomatis"
	label var	CTCYMV	"NP-OP: CT value of Cytomegalovirus"
	label var	CTECSH	"NP-OP: CT value of Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	CTENTV1	"NP-OP: CT value of Enterovirus 1"
	label var	CTENTV2	"NP-OP: CT value of Enterovirus 2"
	label var	CTFLUA	"NP-OP: CT value of Influenza type A"
	label var	CTFLUB	"NP-OP: CT value of Influenza type B"
	label var	CTGADH	"NP-OP: CT value of Glyceraldehyde-3-phosphate dehydrogenase"
	label var	CTGAST	"NP-OP: CT value of Streptococus pyogenes"
	label var	CTGBST	"NP-OP: CT value of Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	CTHIAT	"NP-OP: CT value of Haemophilus infuluenzae"
	label var	CTHITB	"NP-OP: CT value of Haemophilus infuluenzae type B"
	label var	CTHMPV	"NP-OP: CT value of Human Metapneumovirus"
	label var	CTHPEV	"NP-OP: CT value of Parechovirus"
	label var	CTPIV1	"NP-OP: CT value of Parainfluenza virus-1"	
	label var	CTPIV2	"NP-OP: CT value of Parainfluenza virus-2"
	label var	CTPIV3	"NP-OP: CT value of Parainfluenza virus-3"
	label var	CTHSV1	"NP-OP: CT value of Herpes Simplex Virus type 1"
	label var	CTHSV2	"NP-OP: CT value of Herpes Simplex Virus type 2"
	label var	CTIPCO	"NP-OP: CT value of Internal Positive Control"	
	label var	CTKLPN	"NP-OP: CT value of Klebsiella pneumoniae"
	label var	CTMYPN	"NP-OP: CT value of Mycoplasma pneumoniae"
	label var	CTPSAE	"NP-OP: CT value of Pseudomonas aeruginosa"
	label var	CTRESV	"NP-OP: CT value of Respiratory Syncytial Virus"
	label var	CTNMEN	"NP-OP: CT value of Neisseria meningitidis"
	label var	CTRHIV	"NP-OP: CT value of Rhinovirus"
	label var	CTRNP3	"NP-OP: CT value of Human RNase P gene"
	label var	CTRUBV	"NP-OP: CT value of Rubella virus"
	label var	CTSALS	"NP-OP: CT value of Salmonella spp"
	label var	CTSTAU	"NP-OP: CT value of Staphylococcus aureus"
	label var	CTSTPN	"NP-OP: CT value of Streptococcus pneumoniae 1"
	label var	CTTOxG	"NP-OP: CT value of Toxoplasma gondii"
	label var	CTURUP	"NP-OP: CT value of U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"

	label var	CTABAUCat	"NP-OP: CT value classification:  Acinetobacter baumannii"
	label var	CTADEVCat	"NP-OP: CT value classification:  Adenovirus"
	label var	CTBOP1Cat	"NP-OP: CT value classification:  Bordetella pertussis, Bordetella holmesii"
	label var	CTCHPNCat	"NP-OP: CT value classification:  Chlamydophila pneumoniae"
	label var	CTCHTRCat	"NP-OP: CT value classification:  Chlamydia trachomatis"
	label var	CTCYMVCat	"NP-OP: CT value classification:  Cytomegalovirus"
	label var	CTECSHCat	"NP-OP: CT value classification:  Escherichia coli (all), Shigella spp. (except S. dysenteriae serotype I)"
	label var	CTENTV1Cat	"NP-OP: CT value classification:  Enterovirus 1"
	label var	CTENTV2Cat	"NP-OP: CT value classification:  Enterovirus 2"
	label var	CTFLUACat	"NP-OP: CT value classification:  Influenza type A"
	label var	CTFLUBCat	"NP-OP: CT value classification:  Influenza type B"
	label var	CTGADHCat	"NP-OP: CT value classification:  Glyceraldehyde-3-phosphate dehydrogenase"
	label var	CTGASTCat	"NP-OP: CT value classification:  Streptococus pyogenes"
	label var	CTGBSTCat	"NP-OP: CT value classification:  Group B Streptococcus (all serotypes: IA, IB, II, III, IV, V, VI, VII, VIII, IX)"
	label var	CTHIATCat	"NP-OP: CT value classification:  Haemophilus infuluenzae"
	label var	CTHITBCat	"NP-OP: CT value classification:  Haemophilus infuluenzae type B"
	label var	CTHMPVCat	"NP-OP: CT value classification:  Human Metapneumovirus"
	label var	CTHPEVCat	"NP-OP: CT value classification:  Parechovirus"
	label var	CTPIV1Cat	"NP-OP: CT value classification:  Parainfluenza virus-1"	
	label var	CTPIV2Cat	"NP-OP: CT value classification:  Parainfluenza virus-2"
	label var	CTPIV3Cat	"NP-OP: CT value classification:  Parainfluenza virus-3"
	label var	CTHSV1Cat	"NP-OP: CT value classification:  Herpes Simplex Virus type 1"
	label var	CTHSV2Cat	"NP-OP: CT value classification:  Herpes Simplex Virus type 2"
	label var	CTIPCOCat	"NP-OP: CT value classification:  Internal Positive Control"	
	label var	CTKLPNCat	"NP-OP: CT value classification:  Klebsiella pneumoniae"
	label var	CTMYPNCat	"NP-OP: CT value classification:  Mycoplasma pneumoniae"
	label var	CTPSAECat	"NP-OP: CT value classification:  Pseudomonas aeruginosa"
	label var	CTRESVCat	"NP-OP: CT value classification:  Respiratory Syncytial Virus"
	label var	CTNMENCat	"NP-OP: CT value classification:  Neisseria meningitidis"
	label var	CTRHIVCat	"NP-OP: CT value classification:  Rhinovirus"
	label var	CTRNP3Cat	"NP-OP: CT value classification:  Human RNase P gene"
	label var	CTRUBVCat	"NP-OP: CT value classification:  Rubella virus"
	label var	CTSALSCat	"NP-OP: CT value classification:  Salmonella spp"
	label var	CTSTAUCat	"NP-OP: CT value classification:  Staphylococcus aureus"
	label var	CTSTPNCat	"NP-OP: CT value classification:  Streptococcus pneumoniae 1"
	label var	CTTOxGCat	"NP-OP: CT value classification:  Toxoplasma gondii"
	label var	CTURUPCat	"NP-OP: CT value classification:  U. parvum (biovar 1; serovars 1, 3, 6, 14), U. urealyticum (biovar 2; serovars 2, 4, 5, 7-13)"
	label var 	Growth	 	"All Detected in NP-OP TLDA"
	label var 	NoPos	 	"Total number of organisms detected in NP-OP TLDA"
	label var 	expRunDate	"NP-OP TLDA run date"
	}
